### ISSUE TITLE
Allow user to filter view plan

### ISSUE THREAD

**Issue by adfyong** [macewanCS/DreamSolutions#91]
Substories:
- [x] Filter by hierarchy
- [x] Filter by priority
- [x] Filter by goal type
- [x] Filter by dept/team
  - [x] Pull in list of departments and teams
- [x] Filter by lead and collaborator
  - [x] Pull in list of dept/team/users
- [x] Filter by due date
  - [x] Implement date picker for start/end date filtering
- [x] Filter by status
